// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC9ZB7fYfs6qJW_eoqRbhDXxbwL3gN3T0',
    appId: '1:441311833322:web:9ee861bac1fd294860bb93',
    messagingSenderId: '441311833322',
    projectId: 'math-generator-project',
    authDomain: 'math-generator-project.firebaseapp.com',
    storageBucket: 'math-generator-project.appspot.com',
    measurementId: 'G-EY1RXS6Q8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABFFgZPRrozYub4lCkwvF3haEu2-CzQcQ',
    appId: '1:441311833322:android:71e81d86d5b3046c60bb93',
    messagingSenderId: '441311833322',
    projectId: 'math-generator-project',
    storageBucket: 'math-generator-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLLpHtoxI2SnxGrNg1IGX4rtNk79bzpDE',
    appId: '1:441311833322:ios:669731963e2a290360bb93',
    messagingSenderId: '441311833322',
    projectId: 'math-generator-project',
    storageBucket: 'math-generator-project.appspot.com',
    iosClientId: '441311833322-qck0co21bdahr4qtpuhcpgbe84f6ht4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLLpHtoxI2SnxGrNg1IGX4rtNk79bzpDE',
    appId: '1:441311833322:ios:669731963e2a290360bb93',
    messagingSenderId: '441311833322',
    projectId: 'math-generator-project',
    storageBucket: 'math-generator-project.appspot.com',
    iosClientId: '441311833322-qck0co21bdahr4qtpuhcpgbe84f6ht4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
